Fix `theme pull` error message when development theme doesn't exist
fixes `NoMethodError: undefined method 'name'`
```
NoMethodError: undefined method `name' for nil:NilClass
    /Users/johnroyall/shopify-cli-kilgore5/lib/project_types/theme/commands/pull.rb:78:in `find_theme'
```